// Auto-generated by assembler.js - prog_bram init
mem[  0] = 8'h01;
mem[  1] = 8'h3F;
mem[  2] = 8'h00;
mem[  3] = 8'h00;
mem[  4] = 8'h00;
mem[  5] = 8'h01;
mem[  6] = 8'h00;
mem[  7] = 8'hF0;
mem[  8] = 8'hFF;
mem[  9] = 8'hFF;
mem[ 10] = 8'h1E;
mem[ 11] = 8'h0F;
mem[ 12] = 8'h0B;
mem[ 13] = 8'h00;
mem[ 14] = 8'h00;
mem[ 15] = 8'h00;