;;; Conway's Game of Life — 128×64 grid on OLED

(defun grid-get (base x y)
  (let ((page (/ y 8))
        (bit (% y 8)))
    (let ((b (peekb (+ base (+ (* page 128) x)))))
      (>> (logand b (<< 1 bit)) bit))))

(defun grid-set (base x y val)
  (let ((page (/ y 8))
        (bit (% y 8)))
    (let ((addr (+ base (+ (* page 128) x)))
          (old (peekb addr)))
      (if (= val 0)
          (pokeb addr (logand old (lognot (<< 1 bit))))
          (pokeb addr (logor old (<< 1 bit)))))))

(defun count-nbrs (base x y)
  (let ((cnt 0) (dy -1))
    (while (<= dy 1)
      (let ((dx -1))
        (while (<= dx 1)
          (let ((nx (+ x dx)) (ny (+ y dy)))
            (if (and (or (not (= dx 0)) (not (= dy 0)))
                     (and (>= nx 0) (< nx 128) (>= ny 0) (< ny 64)))
                (set! cnt (+ cnt (grid-get base nx ny)))))
          (set! dx (+ dx 1))))
      (set! dy (+ dy 1)))
    cnt))

(defun life-gen (src dst)
  (let ((x 0))
    (while (< x 128)
      (let ((y 0))
        (while (< y 64)
          (let ((n (count-nbrs src x y))
                (a (grid-get src x y)))
            (if (= a 1)
                (if (or (< n 2) (> n 3))
                    (grid-set dst x y 0)
                    (grid-set dst x y 1))
                (if (= n 3)
                    (grid-set dst x y 1)
                    (grid-set dst x y 0))))
          (set! y (+ y 1))))
      (set! x (+ x 1)))))

(defun buf-copy (src dst)
  (let ((i 0))
    (while (< i 1024)
      (pokeb (+ dst i) (peekb (+ src i)))
      (set! i (+ i 1)))))

(defun seed-glider (x y)
  (grid-set #x1000 (+ x 1) y       1)
  (grid-set #x1000 (+ x 2) (+ y 1) 1)
  (grid-set #x1000 x       (+ y 2) 1)
  (grid-set #x1000 (+ x 1) (+ y 2) 1)
  (grid-set #x1000 (+ x 2) (+ y 2) 1))

(seed-glider 5  5)
(seed-glider 20 5)
(seed-glider 35 5)
(seed-glider 50 5)
(seed-glider 10 20)
(seed-glider 25 20)
(seed-glider 40 20)
(seed-glider 55 20)
(seed-glider 15 35)
(seed-glider 30 35)
(seed-glider 45 35)
(seed-glider 60 35)

(let ((gen 0))
  (while (< gen 50)
    (life-gen #x1000 #x2000)
    (buf-copy #x2000 #x1000)
    (pokeb #x10000 0)
    (set! gen (+ gen 1))))