// Auto-generated by assembler.js
// Total bytes: 25

initial begin
    program[  0] = 8'h01;
    program[  1] = 8'h4F;
    program[  2] = 8'h00;
    program[  3] = 8'h00;
    program[  4] = 8'h00;
    program[  5] = 8'h08;
    program[  6] = 8'h01;
    program[  7] = 8'h4B;
    program[  8] = 8'h00;
    program[  9] = 8'h00;
    program[ 10] = 8'h00;
    program[ 11] = 8'h08;
    program[ 12] = 8'h01;
    program[ 13] = 8'h0D;
    program[ 14] = 8'h00;
    program[ 15] = 8'h00;
    program[ 16] = 8'h00;
    program[ 17] = 8'h08;
    program[ 18] = 8'h01;
    program[ 19] = 8'h0A;
    program[ 20] = 8'h00;
    program[ 21] = 8'h00;
    program[ 22] = 8'h00;
    program[ 23] = 8'h08;
    program[ 24] = 8'hFF;
end
