// Auto-generated by assembler.js
// Total bytes: 16

initial begin
    program[  0] = 8'h01;
    program[  1] = 8'h3F;
    program[  2] = 8'h00;
    program[  3] = 8'h00;
    program[  4] = 8'h00;
    program[  5] = 8'h01;
    program[  6] = 8'h00;
    program[  7] = 8'hF0;
    program[  8] = 8'hFF;
    program[  9] = 8'hFF;
    program[ 10] = 8'h1E;
    program[ 11] = 8'h0F;
    program[ 12] = 8'h0B;
    program[ 13] = 8'h00;
    program[ 14] = 8'h00;
    program[ 15] = 8'h00;
end
